name = "xgqn-project"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 使用 Next.js 静态导出 + Cloudflare Pages Functions
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "xgqn-database"
database_id = "be9dac82-904f-459a-8b23-69bc613c8aa1"